export const GET_ELECTRICIAN_DATA_REQUEST = "GET_ELECTRICIAN_DATA_REQUEST";
export const GET_ELECTRICIAN_DATA_SUCCESS = "GET_ELECTRICIAN_DATA_SUCCESS";
export const GET_ELECTRICIAN_DATA_FAILURE = "GET_ELECTRICIAN_DATA_FAILURE";