export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const GET_ELECTRICIAN_DATA_REQUEST = "GET_ELECTRICIAN_DATA_REQUEST";
export const GET_ELECTRICIAN_DATA_SUCCESS = "GET_ELECTRICIAN_DATA_SUCCESS";
export const GET_ELECTRICIAN_DATA_FAILURE = "GET_ELECTRICIAN_DATA_FAILURE";

export const GET_MEN_PRODUCTS_REQUEST = "GET_MEN_PRODUCTS_REQUEST";
export const GET_MEN_PRODUCTS_SUCCESS = "GET_MEN_PRODUCTS_SUCCESS";
export const GET_MEN_PRODUCTS_FAILURE = "GET_MEN_PRODUCTS_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";